server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_email
    username: root
    password: ${password_bd}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

