CREATE TABLE tb_user
(
    id_user  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(30)                             NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    status   VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id_user)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_login UNIQUE (login);