CREATE TABLE tb_professional
(
    id_professional BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    phone           VARCHAR(255)                            NOT NULL,
    cpf             VARCHAR(255)                            NOT NULL,
    admission_date  date                                    NOT NULL,
    updated_date    TIMESTAMP WITHOUT TIME ZONE,
    office          VARCHAR(255)                            NOT NULL,
    surname         VARCHAR(255),
    time_type       VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_tb_professional PRIMARY KEY (id_professional)
);

ALTER TABLE tb_professional
    ADD CONSTRAINT uc_tb_professional_cpf UNIQUE (cpf);

ALTER TABLE tb_professional
    ADD CONSTRAINT uc_tb_professional_email UNIQUE (email);