CREATE TABLE tb_instructor
(
    id_instructor   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cref            VARCHAR(6)                              NOT NULL,
    id_professional BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_instructor PRIMARY KEY (id_instructor)
);

ALTER TABLE tb_instructor
    ADD CONSTRAINT uc_tb_instructor_cref UNIQUE (cref);

ALTER TABLE tb_instructor
    ADD CONSTRAINT FK_TB_INSTRUCTOR_ON_ID_PROFESSIONAL FOREIGN KEY (id_professional) REFERENCES tb_professional (id_professional);