CREATE TABLE tb_receptionist
(
    id_receptionist BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_professional BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_receptionist PRIMARY KEY (id_receptionist)
);

ALTER TABLE tb_receptionist
    ADD CONSTRAINT FK_TB_RECEPTIONIST_ON_ID_PROFESSIONAL FOREIGN KEY (id_professional) REFERENCES tb_professional (id_professional);