CREATE TABLE tb_plan
(
    id_plan        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    price          DECIMAL                                 NOT NULL,
    effective_date date                                    NOT NULL,
    CONSTRAINT pk_tb_plan PRIMARY KEY (id_plan)
);

ALTER TABLE tb_plan
    ADD CONSTRAINT uc_tb_plan_name UNIQUE (name);

ALTER TABLE tb_plan
    ADD CONSTRAINT uc_tb_plan_price UNIQUE (price);