CREATE TABLE tb_payment
(
    id_payment      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_payment    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    value           DECIMAL(8, 2)                           NOT NULL,
    form_payment    VARCHAR(255)                            NOT NULL,
    id_client       BIGINT                                  NOT NULL,
    id_receptionist BIGINT                                  NOT NULL,
    id_plan         BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_payment PRIMARY KEY (id_payment)
);

ALTER TABLE tb_payment
    ADD CONSTRAINT FK_TB_PAYMENT_ON_ID_CLIENT FOREIGN KEY (id_client) REFERENCES tb_client (id_client);

ALTER TABLE tb_payment
    ADD CONSTRAINT FK_TB_PAYMENT_ON_ID_PLAN FOREIGN KEY (id_plan) REFERENCES tb_plan (id_plan);

ALTER TABLE tb_payment
    ADD CONSTRAINT FK_TB_PAYMENT_ON_ID_RECEPTIONIST FOREIGN KEY (id_receptionist) REFERENCES tb_receptionist (id_receptionist);